INSERT INTO cat(name, image_url, selected)
VALUES ('Барсик',
        'https://images.wallpaperscraft.ru/image/single/koshka_kot_seryy_poroda_russkaya_golubaya_glaza_zelenye_vzglyad_chernyy_fon_81774_300x168.jpg',
        0),
       ('Стёпа',
        'https://images.wallpaperscraft.ru/image/single/trava_zelen_koshka_belo_ryzhaya_pushistaya_94020_300x168.jpg',
        0),
       ('Лариса',
        'https://images.wallpaperscraft.ru/image/single/kotyonok_kot_koshka_kompyuter_klaviatura_apple_mac_chb_94218_300x168.jpg',
        0),
       ('Алиса', 'https://images.wallpaperscraft.ru/image/single/koshka_pitomets_zhivotnoe_202736_300x168.jpg', 0),
       ('Лиза', 'https://images.wallpaperscraft.ru/image/single/kot_koshka_kotenok_zabota_nezhnost_95756_300x168.jpg',
        0),
       ('Борис',
        'https://images.wallpaperscraft.ru/image/single/kot_koshka_vesna_gazon_zelen_priroda_81769_300x168.jpg', 0),
       ('Томас', 'https://images.wallpaperscraft.ru/image/single/stena_kirpich_koshka_siamskaya_81790_300x168.jpg', 0),
       ('Маша',
        'https://images.wallpaperscraft.ru/image/single/koshka_kotenok_lezhit_krovat_glaza_vzglyad_poloski_75875_300x168.jpg',
        0),
       ('Ричард', 'https://images.wallpaperscraft.ru/image/single/sherst_meh_usy_morda_lapy_koshka_73893_300x168.jpg',
        0),
       ('Муся', 'https://images.wallpaperscraft.ru/image/single/koshka_derevo_vesna_93133_300x168.jpg', 0)
